CREATE TABLE price_history_locf (
    time TIMESTAMPTZ NOT NULL UNIQUE,
    value DOUBLE PRECISION NOT NULL,
    ma_5 DOUBLE PRECISION,
    ma_60 DOUBLE PRECISION,
    ma_300 DOUBLE PRECISION,
    PRIMARY KEY (time)
);
