CREATE TABLE ohlc_candles (
    time TIMESTAMPTZ NOT NULL PRIMARY KEY ,
    open DOUBLE PRECISION NOT NULL,
    high DOUBLE PRECISION NOT NULL,
    low DOUBLE PRECISION NOT NULL,
    close DOUBLE PRECISION NOT NULL,
    volume BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW (),
    gap BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_ohlc_candles_gaps ON ohlc_candles (gap)
WHERE gap IS TRUE;
